import random
from typing import Dict, List, NamedTuple
from functools import lru_cache
from .models import TableName, TableField, SelectField


class FieldInfo(NamedTuple):
    """Represents a field and its metadata"""
    name: str
    types: List[str]
    synonyms: List[str]


def get_sql_table_fields(table_name: TableName, N: int) -> List[TableField]:
    """Return N random SQL field names with an associated data type."""
    # Get the cached list of field names and their possible types
    field_infos = get_FieldInfo()
    
    # Sample N items from the list, in a random order
    selected_fields = random.sample(list(field_infos.values()), N)

    # For each selected field, choose one random type from its possible types, and one synonym
    answer = [TableField(name=name, type=random.choice(types), synonym=random.choice(synonyms).replace('_',' ')) for name, types, synonyms in selected_fields]

    # If the table name is also a field name, change add "_field" to the field name
    for a_field in answer:
        if a_field.name == table_name.name:
            a_field.name += "_field"

    return answer


def get_sql_select_fields( table_fields : List[TableField], N: int, use_aggregates: bool) -> List[SelectField]:
    """Return N random SQL field names with an associated aggregate."""
    
    # Define which aggregates can be used with which data types
    aggregate_by_type = {
        "INTEGER": ["SUM", "AVG", "MIN", "MAX", "COUNT", ""],
        "BIGINT": ["SUM", "AVG", "MIN", "MAX", "COUNT", ""],
        "DECIMAL": ["SUM", "AVG", "MIN", "MAX", "COUNT", ""],
        "NUMERIC": ["SUM", "AVG", "MIN", "MAX", "COUNT", ""],
        "FLOAT": ["SUM", "AVG", "MIN", "MAX", "COUNT", ""],
        "DOUBLE": ["SUM", "AVG", "MIN", "MAX", "COUNT", ""],
        "VARCHAR": ["MIN", "MAX", "COUNT", ""],
        "CHAR": ["MIN", "MAX", "COUNT", ""],
        "TEXT": ["MIN", "MAX", "COUNT", ""],
        "DATE": ["MIN", "MAX", "COUNT", ""],
        "DATETIME": ["MIN", "MAX", "COUNT", ""],
        "TIMESTAMP": ["MIN", "MAX", "COUNT", ""],
        "BOOLEAN": ["COUNT", ""],
        "UUID": ["COUNT", ""],
        "BLOB": ["COUNT", ""],
        "JSON": ["COUNT", ""],
        "JSONB": ["COUNT", ""]
    }
    
    # Default to all types if type not found
    default_aggregates = ["COUNT", ""]
    
    selected_fields = []   
    for a_table_field in random.sample(table_fields, N):

        field_name = a_table_field.name
        field_type = a_table_field.type.upper()
        field_synonym = a_table_field.synonym
        
        if use_aggregates:
            # Get valid aggregates for this field type
            valid_aggregates = aggregate_by_type.get(field_type, default_aggregates)
            agg = random.choice(valid_aggregates)
            selected_fields += [SelectField(name=field_name, aggregate=agg, synonym=field_synonym)]
        else:
            selected_fields += [SelectField(name=field_name, aggregate="", synonym=field_synonym)]

    return selected_fields


def get_field_names_with_synonyms() -> Dict[str, FieldInfo]:
    return get_FieldInfo()


@lru_cache(maxsize=1)
def get_FieldInfo() -> Dict[str, FieldInfo]:
    """
    Returns a dictionary of common SQL column names and their frequently used data types.
    Each column name maps to a list of common SQL data types for that column.
    """
    return {
        # Primary Keys and IDs
        "id": FieldInfo("id", ["INTEGER", "BIGINT", "SERIAL", "BIGSERIAL"], 
                       ["identifier", "record_number"]),
        "uuid": FieldInfo("uuid", ["UUID", "VARCHAR(36)", "CHAR(36)"], 
                         ["unique_identifier", "global_id"]),
        "guid": FieldInfo("guid", ["VARCHAR(36)", "CHAR(36)"], 
                         ["global_identifier", "universal_id"]),
        "external_id": FieldInfo("external_id", ["VARCHAR(50)", "VARCHAR(100)"], 
                                ["outside_reference", "external_reference"]),
        "reference_id": FieldInfo("reference_id", ["VARCHAR(50)", "VARCHAR(100)"], 
                                 ["reference_number", "ref_code"]),
        "parent_id": FieldInfo("parent_id", ["INTEGER", "BIGINT"], 
                              ["parent_reference", "parent_record"]),
        "source_id": FieldInfo("source_id", ["INTEGER", "BIGINT"],
                              ["origin_id", "source_reference"]),
        "target_id": FieldInfo("target_id", ["INTEGER", "BIGINT"],
                              ["destination_id", "target_reference"]),
        
        # Common Prefixed IDs
        "user_id": FieldInfo("user_id", ["INTEGER", "BIGINT"],
                            ["member_id", "user_reference"]),
        "customer_id": FieldInfo("customer_id", ["INTEGER", "BIGINT"],
                                ["client_id", "patron_id"]),
        "order_id": FieldInfo("order_id", ["INTEGER", "BIGINT"],
                             ["purchase_id", "transaction_reference"]),
        "product_id": FieldInfo("product_id", ["INTEGER", "BIGINT"],
                               ["item_id", "goods_reference"]),
        "account_id": FieldInfo("account_id", ["INTEGER", "BIGINT"],
                               ["profile_id", "account_reference"]),
        "session_id": FieldInfo("session_id", ["VARCHAR(100)", "CHAR(32)"],
                               ["session_key", "connection_id"]),
        "transaction_id": FieldInfo("transaction_id", ["VARCHAR(50)", "VARCHAR(100)"],
                                   ["payment_id", "transaction_reference"]),
        
        # Basic Information
        "name": FieldInfo("name", ["VARCHAR(100)", "VARCHAR(255)"],
                         ["title", "designation"]),
        "description": FieldInfo("description", ["TEXT", "VARCHAR(1000)", "MEDIUMTEXT"],
                                ["details", "explanation"]),
        "summary": FieldInfo("summary", ["TEXT", "VARCHAR(500)"],
                            ["brief", "overview"]),
        "details": FieldInfo("details", ["TEXT", "JSONB", "JSON"],
                            ["specifics", "information"]),
        "content": FieldInfo("content", ["TEXT", "MEDIUMTEXT", "LONGTEXT"],
                            ["body", "text_content"]),
        "notes": FieldInfo("notes", ["TEXT", "VARCHAR(1000)"],
                          ["annotations", "remarks"]),
        "comments": FieldInfo("comments", ["TEXT", "VARCHAR(1000)"],
                             ["feedback", "observations"]),
        "type": FieldInfo("type", ["VARCHAR(50)", "ENUM"],
                         ["category", "classification"]),
        "category": FieldInfo("category", ["VARCHAR(50)", "VARCHAR(100)"],
                             ["group", "classification"]),
        "status": FieldInfo("status", ["VARCHAR(20)", "ENUM", "SMALLINT"],
                           ["state", "condition"]),
        "code": FieldInfo("code", ["VARCHAR(50)", "CHAR(10)"],
                         ["reference_code", "identifier_code"]),
        "slug": FieldInfo("slug", ["VARCHAR(100)", "VARCHAR(255)"],
                         ["url_path", "permalink"]),
        
        # Name Components
        "first_name": FieldInfo("first_name", ["VARCHAR(50)", "VARCHAR(100)"],
                               ["given_name", "forename"]),
        "last_name": FieldInfo("last_name", ["VARCHAR(50)", "VARCHAR(100)"],
                              ["surname", "family_name"]),
        "middle_name": FieldInfo("middle_name", ["VARCHAR(50)", "VARCHAR(100)"],
                                ["middle_initial", "second_name"]),
        "full_name": FieldInfo("full_name", ["VARCHAR(150)", "VARCHAR(255)"],
                              ["complete_name", "entire_name"]),
        "display_name": FieldInfo("display_name", ["VARCHAR(100)", "VARCHAR(255)"],
                                 ["screen_name", "visible_name"]),
        "username": FieldInfo("username", ["VARCHAR(50)", "VARCHAR(100)"],
                             ["login_name", "user_handle"]),
        "nickname": FieldInfo("nickname", ["VARCHAR(50)", "VARCHAR(100)"],
                             ["alias", "preferred_name"]),
        
        # Contact Information
        "email": FieldInfo("email", ["VARCHAR(100)", "VARCHAR(255)"],
                          ["email_address", "mail"]),
        "phone": FieldInfo("phone", ["VARCHAR(20)", "VARCHAR(50)"],
                          ["telephone", "phone_number"]),
        "mobile": FieldInfo("mobile", ["VARCHAR(20)", "VARCHAR(50)"],
                           ["cell_phone", "mobile_number"]),
        "fax": FieldInfo("fax", ["VARCHAR(20)", "VARCHAR(50)"],
                        ["facsimile", "fax_number"]),
        "website": FieldInfo("website", ["VARCHAR(255)", "TEXT"],
                            ["web_address", "url"]),
        
        # Address Components
        "address": FieldInfo("address", ["VARCHAR(255)", "TEXT"],
                            ["location", "street_address"]),
        "address_line1": FieldInfo("address_line1", ["VARCHAR(255)"],
                                  ["street_address", "primary_address"]),
        "address_line2": FieldInfo("address_line2", ["VARCHAR(255)"],
                                  ["suite", "secondary_address"]),
        "street": FieldInfo("street", ["VARCHAR(255)"],
                           ["street_name", "road"]),
        "city": FieldInfo("city", ["VARCHAR(100)"],
                         ["town", "municipality"]),
        "state": FieldInfo("state", ["VARCHAR(100)", "CHAR(2)"],
                          ["province", "region"]),
        "country": FieldInfo("country", ["VARCHAR(100)", "CHAR(2)", "CHAR(3)"],
                            ["nation", "territory"]),
        "postal_code": FieldInfo("postal_code", ["VARCHAR(20)", "CHAR(5)", "CHAR(10)"],
                                ["zip_code", "post_code"]),
        "latitude": FieldInfo("latitude", ["DECIMAL(10,8)", "FLOAT", "DOUBLE"],
                             ["lat", "y_coordinate"]),
        "longitude": FieldInfo("longitude", ["DECIMAL(11,8)", "FLOAT", "DOUBLE"],
                              ["long", "x_coordinate"]),
        
        # Dates and Times
        "created_at": FieldInfo("created_at", ["TIMESTAMP", "DATETIME"],
                               ["creation_date", "date_created"]),
        "updated_at": FieldInfo("updated_at", ["TIMESTAMP", "DATETIME"],
                               ["modification_date", "last_modified"]),
        "deleted_at": FieldInfo("deleted_at", ["TIMESTAMP", "DATETIME"],
                               ["removal_date", "date_deleted"]),
        "modified_at": FieldInfo("modified_at", ["TIMESTAMP", "DATETIME"],
                                ["change_date", "date_modified"]),
        "timestamp": FieldInfo("timestamp", ["TIMESTAMP", "BIGINT"],
                              ["time_stamp", "datetime_mark"]),
        "date": FieldInfo("date", ["DATE"],
                         ["calendar_date", "day"]),
        "time": FieldInfo("time", ["TIME"],
                         ["clock_time", "hour_minute"]),
        "datetime": FieldInfo("datetime", ["DATETIME", "TIMESTAMP"],
                             ["date_time", "timestamp"]),
        "start_date": FieldInfo("start_date", ["DATE", "DATETIME"],
                               ["begin_date", "from_date"]),
        "end_date": FieldInfo("end_date", ["DATE", "DATETIME"],
                             ["finish_date", "to_date"]),
        "duration": FieldInfo("duration", ["INTEGER", "INTERVAL"],
                             ["time_span", "period"]),
        "birthday": FieldInfo("birthday", ["DATE"],
                             ["birth_date", "date_of_birth"]),
        
        # Authentication
        "password": FieldInfo("password", ["VARCHAR(255)", "CHAR(60)"],
                             ["pass_phrase", "security_key"]),
        "password_hash": FieldInfo("password_hash", ["VARCHAR(255)", "CHAR(60)"],
                                  ["hashed_password", "encrypted_password"]),
        "salt": FieldInfo("salt", ["VARCHAR(32)", "CHAR(32)"],
                         ["password_salt", "crypto_salt"]),
        "token": FieldInfo("token", ["VARCHAR(255)", "TEXT"],
                          ["access_token", "security_token"]),
        "api_key": FieldInfo("api_key", ["VARCHAR(100)", "VARCHAR(255)"],
                            ["access_key", "api_token"]),
        "refresh_token": FieldInfo("refresh_token", ["VARCHAR(255)", "TEXT"],
                                  ["renewal_token", "refresh_key"]),
        
        # Status and State
        "is_active": FieldInfo("is_active", ["BOOLEAN", "TINYINT(1)"],
                              ["active_status", "is_enabled"]),
        "is_enabled": FieldInfo("is_enabled", ["BOOLEAN", "TINYINT(1)"],
                               ["enabled_status", "is_available"]),
        "is_deleted": FieldInfo("is_deleted", ["BOOLEAN", "TINYINT(1)"],
                               ["deleted_status", "is_removed"]),
        "is_verified": FieldInfo("is_verified", ["BOOLEAN", "TINYINT(1)"],
                                ["verified_status", "is_confirmed"]),
        "is_default": FieldInfo("is_default", ["BOOLEAN", "TINYINT(1)"],
                               ["default_status", "is_primary"]),
        "is_public": FieldInfo("is_public", ["BOOLEAN", "TINYINT(1)"],
                              ["public_status", "is_visible"]),
        "is_featured": FieldInfo("is_featured", ["BOOLEAN", "TINYINT(1)"],
                                ["featured_status", "is_highlighted"]),
        
        # Numerical Values
        "amount": FieldInfo("amount", ["DECIMAL(10,2)", "NUMERIC(10,2)"],
                           ["sum", "quantity"]),
        "quantity": FieldInfo("quantity", ["INTEGER", "SMALLINT"],
                             ["count", "number"]),
        "total": FieldInfo("total", ["DECIMAL(10,2)", "NUMERIC(10,2)"],
                          ["sum_total", "grand_total"]),
        "balance": FieldInfo("balance", ["DECIMAL(10,2)", "NUMERIC(10,2)"],
                            ["remaining_amount", "current_balance"]),
        "price": FieldInfo("price", ["DECIMAL(10,2)", "NUMERIC(10,2)"],
                          ["cost", "rate"]),
        "cost": FieldInfo("cost", ["DECIMAL(10,2)", "NUMERIC(10,2)"],
                         ["expense", "price"]),
        "rate": FieldInfo("rate", ["DECIMAL(5,2)", "NUMERIC(5,2)"],
                         ["price_rate", "charge_rate"]),
        "percentage": FieldInfo("percentage", ["DECIMAL(5,2)", "NUMERIC(5,2)"],
                               ["percent", "ratio"]),
        "score": FieldInfo("score", ["INTEGER", "DECIMAL(5,2)"],
                          ["points", "rating"]),
        "rank": FieldInfo("rank", ["INTEGER", "SMALLINT"],
                         ["position", "standing"]),
        "count": FieldInfo("count", ["INTEGER", "BIGINT"],
                          ["total_count", "number_of"]),
        
        # Dimensions
        "size": FieldInfo("size", ["VARCHAR(20)", "INTEGER"],
                         ["dimensions", "magnitude"]),
        "width": FieldInfo("width", ["INTEGER", "DECIMAL(10,2)"],
                          ["breadth", "horizontal_size"]),
        "height": FieldInfo("height", ["INTEGER", "DECIMAL(10,2)"],
                           ["vertical_size", "altitude"]),
        "depth": FieldInfo("depth", ["INTEGER", "DECIMAL(10,2)"],
                          ["thickness", "z_dimension"]),
        "weight": FieldInfo("weight", ["DECIMAL(10,2)", "NUMERIC(10,2)"],
                           ["mass", "heaviness"]),
        
        # Financial
        "currency": FieldInfo("currency", ["CHAR(3)", "VARCHAR(3)"],
                             ["money_type", "currency_code"]),
        "currency_code": FieldInfo("currency_code", ["CHAR(3)", "VARCHAR(3)"],
                                  ["currency_type", "money_code"]),
        "exchange_rate": FieldInfo("exchange_rate", ["DECIMAL(10,6)", "NUMERIC(10,6)"],
                                  ["conversion_rate", "forex_rate"]),
        "unit_price": FieldInfo("unit_price", ["DECIMAL(10,2)", "NUMERIC(10,2)"],
                               ["price_per_unit", "individual_price"]),
        "total_price": FieldInfo("total_price", ["DECIMAL(10,2)", "NUMERIC(10,2)"],
                                ["final_price", "total_cost"]),
        "tax_amount": FieldInfo("tax_amount", ["DECIMAL(10,2)", "NUMERIC(10,2)"],
                               ["tax_total", "tax_charge"]),
        
        # Media and Content
        "image": FieldInfo("image", ["VARCHAR(255)", "TEXT"],
                          ["picture", "photo"]),
        "image_url": FieldInfo("image_url", ["VARCHAR(255)", "TEXT"],
                              ["picture_url", "photo_link"]),
        "thumbnail": FieldInfo("thumbnail", ["VARCHAR(255)", "TEXT"],
                              ["small_image", "preview_image"]),
        "file_path": FieldInfo("file_path", ["VARCHAR(255)", "TEXT"],
                              ["document_path", "file_location"]),
        "file_name": FieldInfo("file_name", ["VARCHAR(255)"],
                              ["document_name", "filename"]),
        "file_size": FieldInfo("file_size", ["INTEGER", "BIGINT"],
                              ["document_size", "size_in_bytes"]),
        
        # Metadata
        "meta_title": FieldInfo("meta_title", ["VARCHAR(255)"],
                               ["page_title", "seo_title"]),
        "meta_description": FieldInfo("meta_description", ["TEXT", "VARCHAR(500)"],
                                     ["page_description", "seo_description"]),
        "meta_keywords": FieldInfo("meta_keywords", ["TEXT", "VARCHAR(500)"],
                                  ["page_keywords", "seo_keywords"]),
        "tags": FieldInfo("tags", ["TEXT", "VARCHAR(500)", "JSONB"],
                         ["labels", "keywords"]),
        "sequence": FieldInfo("sequence", ["INTEGER", "SMALLINT"],
                             ["order", "position"]),
        "position": FieldInfo("position", ["INTEGER", "SMALLINT"],
                             ["placement", "rank"]),
        "priority": FieldInfo("priority", ["INTEGER", "SMALLINT"],
                             ["importance", "urgency"]),
        "version": FieldInfo("version", ["INTEGER", "VARCHAR(50)"],
                            ["revision", "release_number"]),
        
        # Configuration
        "settings": FieldInfo("settings", ["TEXT", "JSONB", "JSON"],
                             ["configuration", "preferences"]),
        "preferences": FieldInfo("preferences", ["TEXT", "JSONB", "JSON"],
                                ["user_settings", "options"]),
        "configuration": FieldInfo("configuration", ["TEXT", "JSONB", "JSON"],
                                  ["setup", "parameters"]),
        "options": FieldInfo("options", ["TEXT", "JSONB", "JSON"],
                            ["choices", "parameters"]),
        "properties": FieldInfo("properties", ["TEXT", "JSONB", "JSON"],
                               ["attributes", "characteristics"]),
        
        # System
        "ip_address": FieldInfo("ip_address", ["VARCHAR(45)", "INET"], 
                              ["network_address", "host_address"]),
        "user_agent": FieldInfo("user_agent", ["TEXT", "VARCHAR(500)"],
                               ["browser_info", "client_signature"]),
        "browser": FieldInfo("browser", ["VARCHAR(100)"],
                            ["web_client", "user_browser"]),
        "platform": FieldInfo("platform", ["VARCHAR(50)"],
                             ["system_platform", "operating_environment"]),
        "device_type": FieldInfo("device_type", ["VARCHAR(50)"],
                                ["hardware_type", "device_category"]),
        "language": FieldInfo("language", ["CHAR(2)", "VARCHAR(5)"],
                             ["lang_code", "iso_language"]),
        "locale": FieldInfo("locale", ["VARCHAR(10)", "CHAR(5)"],
                           ["region_code", "language_region"]),
        "timezone": FieldInfo("timezone", ["VARCHAR(50)"],
                             ["time_zone", "tz_name"]),
        
        # Statistics
        "views": FieldInfo("views", ["INTEGER", "BIGINT"],
                          ["page_views", "view_count"]),
        "clicks": FieldInfo("clicks", ["INTEGER", "BIGINT"],
                           ["click_count", "interaction_count"]),
        "impressions": FieldInfo("impressions", ["INTEGER", "BIGINT"],
                                ["view_impressions", "display_count"]),
        "downloads": FieldInfo("downloads", ["INTEGER", "BIGINT"],
                              ["download_count", "file_downloads"]),
        "rating": FieldInfo("rating", ["DECIMAL(3,2)", "NUMERIC(3,2)"],
                           ["score_rating", "star_rating"]),
        "votes": FieldInfo("votes", ["INTEGER", "BIGINT"],
                          ["vote_count", "ballot_count"]),
        
        # Marketing
        "source": FieldInfo("source", ["VARCHAR(100)"],
                           ["traffic_source", "origin_source"]),
        "medium": FieldInfo("medium", ["VARCHAR(100)"],
                           ["traffic_medium", "channel_type"]),
        "campaign": FieldInfo("campaign", ["VARCHAR(100)"],
                             ["marketing_campaign", "promo_campaign"]),
        "referrer": FieldInfo("referrer", ["VARCHAR(255)", "TEXT"],
                             ["referring_url", "traffic_referrer"]),
        "utm_source": FieldInfo("utm_source", ["VARCHAR(100)"],
                               ["tracking_source", "campaign_source"]),
        "utm_medium": FieldInfo("utm_medium", ["VARCHAR(100)"],
                               ["tracking_medium", "campaign_medium"]),
        "utm_campaign": FieldInfo("utm_campaign", ["VARCHAR(100)"],
                                 ["tracking_campaign", "campaign_name"]),
        
        # Binary Data
        "data": FieldInfo("data", ["BLOB", "BYTEA", "BINARY"],
                         ["binary_data", "raw_content"]),
        "content_blob": FieldInfo("content_blob", ["BLOB", "BYTEA", "BINARY"],
                                 ["binary_content", "blob_data"]),
        "signature": FieldInfo("signature", ["BLOB", "BYTEA", "BINARY"],
                              ["digital_signature", "crypto_signature"]),
        
        # Geographical
        "coordinates": FieldInfo("coordinates", ["POINT", "GEOMETRY"],
                                ["geo_coordinates", "spatial_point"]),
        "location": FieldInfo("location", ["POINT", "GEOMETRY"],
                             ["geo_location", "spatial_location"]),
        "area": FieldInfo("area", ["POLYGON", "GEOMETRY"],
                         ["region_area", "spatial_area"]),
        "region": FieldInfo("region", ["VARCHAR(100)", "GEOMETRY"],
                           ["geographic_region", "spatial_region"]),
        
        # Miscellaneous
        "color": FieldInfo("color", ["VARCHAR(20)", "CHAR(7)"],
                          ["color_code", "hex_color"]),
        "format": FieldInfo("format", ["VARCHAR(50)"],
                           ["file_format", "data_format"]),
        "reason": FieldInfo("reason", ["VARCHAR(255)", "TEXT"],
                           ["explanation", "justification"]),
        "result": FieldInfo("result", ["VARCHAR(255)", "TEXT"],
                           ["outcome", "conclusion"]),
        "response": FieldInfo("response", ["TEXT", "JSONB"],
                             ["reply", "answer_data"]),
        "feedback": FieldInfo("feedback", ["TEXT"],
                             ["user_feedback", "response_comment"]),
        "hash": FieldInfo("hash", ["CHAR(32)", "CHAR(40)", "CHAR(64)"],
                         ["checksum", "hash_value"]),
        "province": FieldInfo("province", ["VARCHAR(100)", "TEXT"],
                             ["state", "territory"]),
        "zip_code": FieldInfo("zip_code", ["VARCHAR(20)", "TEXT"],
                             ["postal_code", "pin_code"]),
        "date_of_birth": FieldInfo("date_of_birth", ["DATE"],
                                  ["birth_date", "birthday"]),
        "birth_date": FieldInfo("birth_date", ["DATE"],
                               ["date_of_birth", "birthday"]),
        "age": FieldInfo("age", ["INTEGER", "SMALLINT"],
                        ["years_old", "age_in_years"]),
        "gender": FieldInfo("gender", ["VARCHAR(10)", "CHAR(1)"],
                           ["sex", "gender_identity"]),
        "last_login": FieldInfo("last_login", ["TIMESTAMP", "DATETIME"],
                               ["last_access", "latest_login"]),
        "title": FieldInfo("title", ["VARCHAR(255)", "TEXT"],
                          ["heading", "name"]),
        "body": FieldInfo("body", ["TEXT"],
                         ["content", "main_text"]),
        "excerpt": FieldInfo("excerpt", ["TEXT"],
                            ["preview", "snippet"]),
        "subtotal": FieldInfo("subtotal", ["DECIMAL(10,2)", "FLOAT"],
                             ["partial_total", "pre_tax_total"]),
        "tax": FieldInfo("tax", ["DECIMAL(10,2)", "FLOAT"],
                        ["tax_amount", "tax_value"]),
        "discount": FieldInfo("discount", ["DECIMAL(10,2)", "FLOAT"],
                             ["reduction", "savings"]),
        "points": FieldInfo("points", ["INTEGER", "SMALLINT"],
                           ["score", "credits"]),
        "level": FieldInfo("level", ["INTEGER", "SMALLINT"],
                          ["tier", "rank"]),
        "tag": FieldInfo("tag", ["VARCHAR(50)", "TEXT"],
                        ["label", "keyword"]),
        "note": FieldInfo("note", ["TEXT"],
                         ["comment", "remark"]),
        "comment": FieldInfo("comment", ["TEXT"],
                            ["note", "feedback"]),
        "message": FieldInfo("message", ["TEXT"],
                            ["content", "text"]),
        "url": FieldInfo("url", ["VARCHAR(2083)", "TEXT"],
                        ["link", "web_address"]),
        "link": FieldInfo("link", ["VARCHAR(2083)", "TEXT"],
                         ["url", "href"]),
        "device": FieldInfo("device", ["VARCHAR(255)", "TEXT"],
                           ["hardware", "device_type"]),
        "operating_system": FieldInfo("operating_system", ["VARCHAR(255)", "TEXT"],
                                     ["os", "platform"]),
        "altitude": FieldInfo("altitude", ["DECIMAL(9,6)", "FLOAT"],
                             ["height", "elevation"]),
        "speed": FieldInfo("speed", ["DECIMAL(9,6)", "FLOAT"],
                          ["velocity", "rate"]),
        "direction": FieldInfo("direction", ["DECIMAL(9,6)", "FLOAT"],
                              ["heading", "bearing"]),
        "start_time": FieldInfo("start_time", ["TIME"],
                               ["begin_time", "commencement_time"]),
        "end_time": FieldInfo("end_time", ["TIME"],
                             ["finish_time", "completion_time"]),
        "expires_at": FieldInfo("expires_at", ["TIMESTAMP", "DATETIME"],
                               ["expiration_date", "valid_until"]),
        "is_published": FieldInfo("is_published", ["BOOLEAN", "TINYINT(1)"],
                                 ["published_status", "is_public"]),
        "is_admin": FieldInfo("is_admin", ["BOOLEAN", "TINYINT(1)"],
                             ["admin_status", "is_administrator"]),
        "role": FieldInfo("role", ["VARCHAR(50)", "TEXT"],
                         ["user_role", "permission_level"]),
        "permissions": FieldInfo("permissions", ["TEXT"],
                                ["access_rights", "privileges"]),
        "metadata": FieldInfo("metadata", ["JSON", "TEXT"],
                             ["meta_info", "attributes"]),
        "config": FieldInfo("config", ["JSON", "TEXT"],
                           ["configuration", "setup"]),
        "mime_type": FieldInfo("mime_type", ["VARCHAR(100)", "TEXT"],
                              ["content_type", "file_type"]),
        "phone_number": FieldInfo("phone_number", ["VARCHAR(20)", "TEXT"],
                                 ["telephone", "contact_number"]),
        "mobile_number": FieldInfo("mobile_number", ["VARCHAR(20)", "TEXT"],
                                  ["cell_number", "mobile_phone"]),
        "fax_number": FieldInfo("fax_number", ["VARCHAR(20)", "TEXT"],
                               ["facsimile", "fax"]),
        "company": FieldInfo("company", ["VARCHAR(255)", "TEXT"],
                            ["organization", "business"]),
        "organization": FieldInfo("organization", ["VARCHAR(255)", "TEXT"],
                                 ["company", "institution"]),
        "department": FieldInfo("department", ["VARCHAR(255)", "TEXT"],
                               ["division", "unit"]),
        "job_title": FieldInfo("job_title", ["VARCHAR(100)", "TEXT"],
                              ["position", "role_title"]),
        "salary": FieldInfo("salary", ["DECIMAL(10,2)", "FLOAT"],
                           ["wage", "compensation"]),
        "date_hired": FieldInfo("date_hired", ["DATE"],
                               ["hire_date", "employment_date"]),
        "date_fired": FieldInfo("date_fired", ["DATE"],
                               ["termination_date", "end_date"]),
        "supervisor_id": FieldInfo("supervisor_id", ["INTEGER", "BIGINT"],
                                  ["manager_id", "boss_id"]),
        "manager_id": FieldInfo("manager_id", ["INTEGER", "BIGINT"],
                               ["supervisor_id", "lead_id"]),
        "category_id": FieldInfo("category_id", ["INTEGER", "BIGINT"],
                                ["group_id", "classification_id"]),
        "api_secret": FieldInfo("api_secret", ["VARCHAR(255)", "TEXT"],
                               ["secret_key", "api_password"]),
        "access_token": FieldInfo("access_token", ["VARCHAR(255)", "TEXT"],
                                 ["auth_token", "bearer_token"]),
        "subject": FieldInfo("subject", ["VARCHAR(255)", "TEXT"],
                            ["topic", "title"]),
        "attachment": FieldInfo("attachment", ["VARCHAR(255)", "TEXT"],
                               ["file", "attached_file"]),
        "serial_number": FieldInfo("serial_number", ["VARCHAR(100)", "TEXT"],
                                  ["serial", "sequence_number"]),
        "model": FieldInfo("model", ["VARCHAR(100)", "TEXT"],
                          ["model_number", "product_model"]),
        "manufacturer": FieldInfo("manufacturer", ["VARCHAR(255)", "TEXT"],
                                 ["maker", "producer"]),
        "brand": FieldInfo("brand", ["VARCHAR(100)", "TEXT"],
                          ["make", "trademark"]),
        "sku": FieldInfo("sku", ["VARCHAR(100)", "TEXT"],
                        ["stock_code", "product_code"]),
        "upc": FieldInfo("upc", ["VARCHAR(12)", "TEXT"],
                        ["barcode", "universal_product_code"]),
        "ean": FieldInfo("ean", ["VARCHAR(13)", "TEXT"],
                        ["european_article_number", "international_article_number"]),
        "isbn": FieldInfo("isbn", ["VARCHAR(13)", "TEXT"],
                         ["book_number", "international_standard_book_number"]),
        "release_date": FieldInfo("release_date", ["DATE"],
                                 ["launch_date", "publication_date"]),
        "publish_date": FieldInfo("publish_date", ["DATE"],
                                 ["release_date", "publication_date"]),
        "start_datetime": FieldInfo("start_datetime", ["DATETIME", "TIMESTAMP"],
                                   ["begin_datetime", "start_time"]),
        "end_datetime": FieldInfo("end_datetime", ["DATETIME", "TIMESTAMP"],
                                 ["finish_datetime", "end_time"]),
        "approved_at": FieldInfo("approved_at", ["TIMESTAMP", "DATETIME"],
                                ["approval_date", "authorization_date"]),
        "published_at": FieldInfo("published_at", ["TIMESTAMP", "DATETIME"],
                                 ["release_date", "go_live_date"]),
        "archived_at": FieldInfo("archived_at", ["TIMESTAMP", "DATETIME"],
                                ["archive_date", "storage_date"]),
        "ip": FieldInfo("ip", ["VARCHAR(45)", "TEXT"],
                       ["ip_address", "network_address"]),
        "mac_address": FieldInfo("mac_address", ["VARCHAR(17)", "CHAR(17)"],
                                ["physical_address", "hardware_address"]),
        "accuracy": FieldInfo("accuracy", ["DECIMAL(5,2)", "FLOAT"],
                             ["precision", "exactness"]),
        "heading": FieldInfo("heading", ["DECIMAL(5,2)", "FLOAT"],
                            ["direction", "bearing"]),
        "nationality": FieldInfo("nationality", ["VARCHAR(100)", "TEXT"],
                                ["citizenship", "national_origin"]),
        "marital_status": FieldInfo("marital_status", ["VARCHAR(20)", "TEXT"],
                                   ["civil_status", "relationship_status"]),
        "spouse_name": FieldInfo("spouse_name", ["VARCHAR(255)", "TEXT"],
                                ["partner_name", "married_name"]),
        "children": FieldInfo("children", ["INTEGER", "SMALLINT"],
                             ["dependents", "offspring"]),
        "emergency_contact": FieldInfo("emergency_contact", ["VARCHAR(255)", "TEXT"],
                                      ["urgent_contact", "backup_contact"]),
        "relation": FieldInfo("relation", ["VARCHAR(50)", "TEXT"],
                             ["relationship", "connection"]),
        "education": FieldInfo("education", ["VARCHAR(255)", "TEXT"],
                              ["academic_background", "qualification"]),
        "degree": FieldInfo("degree", ["VARCHAR(100)", "TEXT"],
                           ["qualification", "academic_degree"]),
        "major": FieldInfo("major", ["VARCHAR(100)", "TEXT"],
                          ["specialization", "field_of_study"]),
        "gpa": FieldInfo("gpa", ["DECIMAL(3,2)", "FLOAT"],
                        ["grade_point_average", "academic_score"]),
        "school": FieldInfo("school", ["VARCHAR(255)", "TEXT"],
                           ["institution", "academy"]),
        "university": FieldInfo("university", ["VARCHAR(255)", "TEXT"],
                               ["college", "institute"]),
        "year_graduated": FieldInfo("year_graduated", ["YEAR", "INTEGER"],
                                   ["graduation_year", "completion_year"]),
        "skills": FieldInfo("skills", ["TEXT"],
                           ["capabilities", "competencies"]),
        "experience": FieldInfo("experience", ["TEXT"],
                               ["work_history", "background"]),
        "certification": FieldInfo("certification", ["VARCHAR(255)", "TEXT"],
                                  ["certificate", "qualification"]),
        "license": FieldInfo("license", ["VARCHAR(255)", "TEXT"],
                            ["permit", "authorization"]),
        "availability": FieldInfo("availability", ["VARCHAR(50)", "TEXT"],
                                 ["accessible_time", "free_time"]),
        "reference": FieldInfo("reference", ["TEXT"],
                              ["recommendation", "referral"]),
        "progress": FieldInfo("progress", ["DECIMAL(5,2)", "FLOAT"],
                             ["completion", "advancement"]),
        "milestone": FieldInfo("milestone", ["VARCHAR(255)", "TEXT"],
                              ["achievement", "checkpoint"]),
        "due_date": FieldInfo("due_date", ["DATE"],
                             ["deadline", "target_date"]),
        "completed_at": FieldInfo("completed_at", ["TIMESTAMP", "DATETIME"],
                                 ["finish_time", "completion_date"]),
        "grade": FieldInfo("grade", ["VARCHAR(2)", "CHAR(2)"],
                          ["mark", "score"]),
        "passed": FieldInfo("passed", ["BOOLEAN", "TINYINT(1)"],
                           ["succeeded", "qualified"]),
        "failed": FieldInfo("failed", ["BOOLEAN", "TINYINT(1)"],
                           ["unsuccessful", "not_passed"]),
        "attempts": FieldInfo("attempts", ["INTEGER", "SMALLINT"],
                             ["tries", "trials"]),
        "verified_at": FieldInfo("verified_at", ["TIMESTAMP", "DATETIME"],
                                ["confirmation_date", "validation_time"]),
        "reset_at": FieldInfo("reset_at", ["TIMESTAMP", "DATETIME"],
                             ["restart_time", "clear_time"]),
        "provider": FieldInfo("provider", ["VARCHAR(50)", "TEXT"],
                             ["service_provider", "vendor"]),
        "os_version": FieldInfo("os_version", ["VARCHAR(50)", "TEXT"],
                               ["system_version", "platform_release"]),
        "app_version": FieldInfo("app_version", ["VARCHAR(50)", "TEXT"],
                                ["software_version", "release_version"]),
        "build_number": FieldInfo("build_number", ["INTEGER", "SMALLINT"],
                                 ["version_number", "release_build"]),
        "push_token": FieldInfo("push_token", ["VARCHAR(255)", "TEXT"],
                               ["notification_token", "device_token"]),
        "is_read": FieldInfo("is_read", ["BOOLEAN", "TINYINT(1)"],
                            ["viewed_status", "read_status"]),
        "read_at": FieldInfo("read_at", ["TIMESTAMP", "DATETIME"],
                            ["view_time", "reading_time"]),
        "unread_count": FieldInfo("unread_count", ["INTEGER", "SMALLINT"],
                                 ["pending_items", "unseen_count"]),
        "last_message": FieldInfo("last_message", ["TEXT"],
                                 ["recent_message", "latest_communication"]),
        "last_message_at": FieldInfo("last_message_at", ["TIMESTAMP", "DATETIME"],
                                    ["recent_message_time", "latest_message_date"]),
        "member_count": FieldInfo("member_count", ["INTEGER", "SMALLINT"],
                                 ["participant_count", "user_total"]),
        "owner_id": FieldInfo("owner_id", ["INTEGER", "BIGINT"],
                             ["creator_id", "proprietor_id"]),
        "admin_id": FieldInfo("admin_id", ["INTEGER", "BIGINT"],
                             ["administrator_id", "moderator_id"]),
        "group_id": FieldInfo("group_id", ["INTEGER", "BIGINT"],
                             ["team_id", "collection_id"]),
        "team_id": FieldInfo("team_id", ["INTEGER", "BIGINT"],
                            ["squad_id", "group_id"]),
        "project_id": FieldInfo("project_id", ["INTEGER", "BIGINT"],
                               ["initiative_id", "venture_id"]),
        "task_id": FieldInfo("task_id", ["INTEGER", "BIGINT"],
                            ["activity_id", "assignment_id"]),
        "parent_task_id": FieldInfo("parent_task_id", ["INTEGER", "BIGINT"],
                                   ["main_task_id", "root_task_id"]),
        "label": FieldInfo("label", ["VARCHAR(50)", "TEXT"],
                          ["tag", "marker"]),
        "estimated_time": FieldInfo("estimated_time", ["INTEGER", "SMALLINT"],
                                   ["planned_duration", "expected_time"]),
        "actual_time": FieldInfo("actual_time", ["INTEGER", "SMALLINT"],
                                ["real_duration", "spent_time"]),
        "file_id": FieldInfo("file_id", ["INTEGER", "BIGINT"],
                            ["document_id", "attachment_id"]),
        "media_id": FieldInfo("media_id", ["INTEGER", "BIGINT"],
                             ["content_id", "asset_id"]),
        "image_id": FieldInfo("image_id", ["INTEGER", "BIGINT"],
                             ["picture_id", "photo_id"]),
        "video_id": FieldInfo("video_id", ["INTEGER", "BIGINT"],
                             ["clip_id", "footage_id"]),
        "document_id": FieldInfo("document_id", ["INTEGER", "BIGINT"],
                                ["file_id", "paper_id"]),
        "album_id": FieldInfo("album_id", ["INTEGER", "BIGINT"],
                             ["collection_id", "gallery_id"]),
        "playlist_id": FieldInfo("playlist_id", ["INTEGER", "BIGINT"],
                                ["queue_id", "tracklist_id"]),
        "genre_id": FieldInfo("genre_id", ["INTEGER", "BIGINT"],
                             ["category_id", "style_id"]),
        "like_id": FieldInfo("like_id", ["INTEGER", "BIGINT"],
                            ["appreciation_id", "favorite_id"]),
        "share_id": FieldInfo("share_id", ["INTEGER", "BIGINT"],
                             ["distribution_id", "spread_id"]),
        "reaction": FieldInfo("reaction", ["VARCHAR(20)", "TEXT"],
                             ["emoji_response", "sentiment"]),
        "message_id": FieldInfo("message_id", ["INTEGER", "BIGINT"],
                               ["communication_id", "text_id"]),
        "chat_id": FieldInfo("chat_id", ["INTEGER", "BIGINT"],
                            ["conversation_id", "dialogue_id"]),
        "thread_id": FieldInfo("thread_id", ["INTEGER", "BIGINT"],
                              ["discussion_id", "conversation_chain"]),
        "post_id": FieldInfo("post_id", ["INTEGER", "BIGINT"],
                            ["entry_id", "article_id"]),
        "blog_id": FieldInfo("blog_id", ["INTEGER", "BIGINT"],
                            ["weblog_id", "journal_id"]),
        "forum_id": FieldInfo("forum_id", ["INTEGER", "BIGINT"],
                             ["board_id", "discussion_board"]),
        "topic_id": FieldInfo("topic_id", ["INTEGER", "BIGINT"],
                             ["subject_id", "theme_id"]),
        "vote_id": FieldInfo("vote_id", ["INTEGER", "BIGINT"],
                            ["ballot_id", "poll_response"]),
        "poll_id": FieldInfo("poll_id", ["INTEGER", "BIGINT"],
                            ["survey_id", "questionnaire_id"]),
        "survey_id": FieldInfo("survey_id", ["INTEGER", "BIGINT"],
                              ["questionnaire_id", "feedback_form"]),
        "response_id": FieldInfo("response_id", ["INTEGER", "BIGINT"],
                                ["answer_id", "reply_id"]),
        "question": FieldInfo("question", ["TEXT"],
                             ["inquiry", "query"]),
        "answer": FieldInfo("answer", ["TEXT"],
                           ["response", "reply"]),
        "option": FieldInfo("option", ["TEXT"],
                           ["choice", "selection"]),
        "choice": FieldInfo("choice", ["TEXT"],
                           ["selection", "preference"]),
        "selected": FieldInfo("selected", ["BOOLEAN", "TINYINT(1)"],
                             ["chosen", "picked"]),
        "correct": FieldInfo("correct", ["BOOLEAN", "TINYINT(1)"],
                            ["accurate", "right"]),
        "max_score": FieldInfo("max_score", ["INTEGER", "SMALLINT"],
                              ["highest_points", "maximum_points"]),
        "min_score": FieldInfo("min_score", ["INTEGER", "SMALLINT"],
                              ["lowest_points", "minimum_points"]),
        "average_score": FieldInfo("average_score", ["DECIMAL(5,2)", "FLOAT"],
                                  ["mean_points", "typical_score"]),
        "pass_score": FieldInfo("pass_score", ["DECIMAL(5,2)", "FLOAT"],
                               ["passing_grade", "threshold_points"]),
        "time_limit": FieldInfo("time_limit", ["INTEGER", "SMALLINT"],
                               ["duration_cap", "max_duration"]),
        "time_taken": FieldInfo("time_taken", ["INTEGER", "SMALLINT"],
                               ["elapsed_time", "duration_spent"]),
        "started_at": FieldInfo("started_at", ["TIMESTAMP", "DATETIME"],
                               ["begin_time", "commencement_time"]),
        "finished_at": FieldInfo("finished_at", ["TIMESTAMP", "DATETIME"],
                                ["end_time", "completion_time"])
}

def get_field_names_count():
    return len(get_FieldInfo())