import random
from typing import List
from functools import lru_cache


@lru_cache(maxsize=1)
def get_sql_table_names() -> List[str]:
    """
    Returns a cached list of unique SQL table names.
    Only computes the combination and deduplication once.
    """
    combined_names = get_common_sql_table_names_claude() + get_sql_table_names_chatgpt()
    # Use dict.fromkeys instead of set for stable ordering
    return list(dict.fromkeys(combined_names))


@lru_cache(maxsize=1)
def get_common_sql_table_names_claude():
    """Returns a list of common SQL table names encountered in database schemas."""
    
    return [
        # User-related tables
        "users",
        "user_profiles",
        "user_preferences",
        "user_settings",
        "user_roles",
        "user_permissions",
        "user_sessions",
        "user_logs",
        "user_activity",
        "user_metrics",
        
        # Authentication & Authorization
        "accounts",
        "roles",
        "permissions",
        "auth_tokens",
        "login_attempts",
        "password_reset_tokens",
        "access_logs",
        "security_events",
        
        # Content Management
        "posts",
        "articles",
        "comments",
        "categories",
        "tags",
        "media",
        "attachments",
        "documents",
        "pages",
        "content_revisions",
        
        # E-commerce
        "products",
        "product_categories",
        "product_variants",
        "inventory",
        "orders",
        "order_items",
        "order_status",
        "shopping_cart",
        "cart_items",
        "wishlist",
        "prices",
        "discounts",
        "promotions",
        "coupons",
        
        # Customer Relations
        "customers",
        "customer_addresses",
        "customer_preferences",
        "customer_support_tickets",
        "feedback",
        "complaints",
        "reviews",
        "ratings",
        
        # Financial
        "transactions",
        "payments",
        "payment_methods",
        "invoices",
        "invoice_items",
        "refunds",
        "subscriptions",
        "subscription_plans",
        "billing_cycles",
        "payment_history",
        
        # Shipping
        "shipping_addresses",
        "shipping_methods",
        "shipping_zones",
        "shipping_rates",
        "delivery_status",
        "tracking_info",
        
        # Employee/HR
        "employees",
        "departments",
        "positions",
        "salary_info",
        "attendance",
        "leave_requests",
        "performance_reviews",
        "training_records",
        
        # Communication
        "messages",
        "conversations",
        "chat_rooms",
        "notifications",
        "email_templates",
        "sms_logs",
        "push_notifications",
        
        # Analytics
        "page_views",
        "events",
        "event_logs",
        "metrics",
        "analytics_data",
        "user_behavior",
        "conversion_funnel",
        "ab_test_results",
        
        # Location
        "countries",
        "regions",
        "cities",
        "addresses",
        "locations",
        "geo_data",
        "zip_codes",
        "postal_codes",
        
        # System
        "settings",
        "configurations",
        "system_logs",
        "error_logs",
        "audit_trail",
        "cache",
        "jobs",
        "queues",
        "scheduled_tasks",
        
        # Social
        "followers",
        "following",
        "friend_requests",
        "relationships",
        "groups",
        "group_members",
        "social_connections",
        
        # Blog/CMS
        "blog_posts",
        "blog_categories",
        "blog_tags",
        "authors",
        "publications",
        "drafts",
        "revisions",
        
        # Project Management
        "projects",
        "tasks",
        "milestones",
        "assignments",
        "time_tracking",
        "resources",
        "project_members",
        "sprints",
        
        # Calendar/Events
        "events",
        "event_attendees",
        "calendars",
        "appointments",
        "schedules",
        "reminders",
        "bookings",
        
        # Support/Help
        "faq",
        "help_articles",
        "support_tickets",
        "knowledge_base",
        "tutorials",
        "documentation",
        
        # Inventory Management
        "warehouses",
        "stock_items",
        "suppliers",
        "purchase_orders",
        "stock_movements",
        "inventory_adjustments",
        
        # Media Management
        "images",
        "videos",
        "audio",
        "albums",
        "galleries",
        "playlists",
        "media_metadata",
        
        # Reports
        "reports",
        "report_templates",
        "dashboards",
        "statistics",
        "analytics",
        "insights",
        
        # Security
        "blacklist",
        "whitelist",
        "ip_blocks",
        "security_rules",
        "firewall_logs",
        "vulnerability_scans",
        
        # Integration
        "api_keys",
        "webhooks",
        "external_services",
        "integrations",
        "sync_logs",
        
        # Misc Business
        "vendors",
        "partners",
        "affiliates",
        "contracts",
        "agreements",
        "policies",
        
        # Testing
        "test_cases",
        "test_results",
        "test_runs",
        "test_suites",
        "bug_reports",
        "qa_metrics",
        
        # Device Management
        "devices",
        "device_logs",
        "device_tokens",
        "device_settings",
        "mobile_devices",
        
        # Localization
        "translations",
        "languages",
        "locales",
        "currency_rates",
        "time_zones",
        
        # Temporary/System
        "temp_data",
        "cache_items",
        "session_data",
        "migrations",
        "backups",
        
        # Marketing
        "campaigns",
        "marketing_emails",
        "subscribers",
        "mailing_lists",
        "leads",
        "conversions",
        
        # Logging
        "activity_logs",
        "change_logs",
        "debug_logs",
        "error_reports",
        "performance_logs",
        
        # Version Control
        "versions",
        "changelog",
        "releases",
        "patches",
        "updates"
    ]


@lru_cache(maxsize=1)
def get_sql_table_names_chatgpt():
    table_names = [
        "users",
        "customers",
        "orders",
        "products",
        "employees",
        "departments",
        "sales",
        "inventory",
        "suppliers",
        "categories",
        "transactions",
        "accounts",
        "logs",
        "events",
        "messages",
        "payments",
        "invoices",
        "shipments",
        "reviews",
        "likes",
        "comments",
        "posts",
        "articles",
        "settings",
        "roles",
        "permissions",
        "sessions",
        "profiles",
        "addresses",
        "locations",
        "feedback",
        "notifications",
        "devices",
        "analytics",
        "reports",
        "schedules",
        "tasks",
        "projects",
        "tickets",
        "chat",
        "files",
        "media",
        "images",
        "videos",
        "documents",
        "newsletters",
        "subscriptions",
        "order_items",
        "cart",
        "wishlist",
        "coupons",
        "discounts",
        "promotions",
        "affiliates",
        "leads",
        "opportunities",
        "support_tickets",
        "helpdesk",
        "audit_log",
        "error_log",
        "system_events",
        "user_activity",
        "api_keys",
        "oauth_tokens",
        "connections",
        "relationships",
        "friends",
        "followers",
        "tags",
        "labels",
        "groups",
        "teams",
        "organizations",
        "companies",
        "branches",
        "grades",
        "students",
        "teachers",
        "classes",
        "courses",
        "exams",
        "assignments",
        "lessons",
        "attendance",
        "performance",
        "ranking",
        "blogs",
        "forums",
        "topics",
        "threads",
        "replies",
        "polls",
        "votes",
        "surveys",
        "responses",
        "templates",
        "themes",
        "styles",
        "configuration",
        "parameters",
        "exceptions",
        "debug",
        "metrics",
        "statistics",
        "milestones",
        "phases",
        "steps",
        "stages",
        "resources",
        "assets",
        "materials",
        "equipment",
        "sku",
        "stock",
        "purchases",
        "receipts",
        "refunds",
        "returns",
        "tracking",
        "delivery",
        "logistics",
        "carriers",
        "warehouses",
        "stores",
        "outlets",
        "regions",
        "countries",
        "cities",
        "zipcodes",
        "contacts",
        "phones",
        "emails",
        "social_media",
        "avatars",
        "identities",
        "authentication",
        "authorization",
        "access_control",
        "history",
        "changes",
        "versions",
        "revisions",
        "backups",
        "snapshots",
        "archives",
        "cookies",
        "cache",
        "temp",
        "queue",
        "jobs",
        "cron",
        "schedule",
        "alerts",
        "sms",
        "push_notifications",
        "campaigns",
        "marketing",
        "ads",
        "banners",
        "offers",
        "codes",
        "loyalty",
        "rewards",
        "points",
        "achievements",
        "badges",
        "levels",
        "ranks",
        "scores",
        "leaderboards",
        "dashboards",
        "charts",
        "graphs",
        "datasets",
        "sources",
        "feeds",
        "imports",
        "exports",
        "transformations",
        "mappings",
        "schemas",
        "models",
        "entities",
        "attributes",
        "relations",
        "indexes",
        "constraints",
        "triggers",
        "functions",
        "procedures",
        "policies",
        "rules",
        "statuses",
        "states",
        "modes",
        "annotations",
        "notes",
        "descriptions",
        "summaries",
        "overviews",
        "details",
        "contents",
        "folders",
        "directories",
        "paths",
        "urls",
        "links",
        "networks",
        "nodes",
        "edges",
        "maps",
        "coordinates",
        "geolocation",
        "weather",
        "climate",
        "environment",
        "energy",
        "consumption",
        "usage",
        "cost",
        "price",
        "value",
        "currency",
        "exchange_rates",
        "finance",
        "accounting",
        "budgets",
        "expenses",
        "revenue",
        "income",
        "profit",
        "loss",
        "balance_sheet",
        "cash_flow",
        "liabilities",
        "equity",
        "investments",
        "portfolios",
        "funds",
        "stocks",
        "bonds",
        "commodities",
        "options",
        "futures",
        "derivatives",
        "risk",
        "insurance",
        "claims",
        "coverage",
        "premiums",
        "benefits",
        "healthcare",
        "patients",
        "doctors",
        "appointments",
        "prescriptions",
        "medications",
        "treatments",
        "diagnosis",
        "symptoms",
        "conditions",
        "diseases",
        "allergies",
        "tests",
        "lab_results",
        "medical_records",
        "family_history",
        "lifestyle",
        "habits",
        "fitness",
        "exercise",
        "diet",
        "nutrition",
        "recipes",
        "ingredients",
        "meals",
        "restaurants",
        "recommendations",
        "matches",
        "games",
        "sports",
        "coaches",
        "leagues",
        "tournaments",
        "standings",
        "tickets",
        "venues",
        "music",
        "artists",
        "albums",
        "tracks",
        "genres",
        "playlists",
        "podcasts",
        "episodes",
        "shows",
        "movies",
        "tv_shows",
        "series",
        "actors",
        "directors",
        "producers",
        "studios",
        "box_office",
        "awards",
        "nominations",
        "elections",
        "candidates",
        "parties",
        "results",
        "suggestions",
        "complaints",
        "issues",
        "knowledge_base",
        "faqs",
        "guides",
        "tutorials",
        "documentation",
        "blog_posts",
        "news",
        "press_releases",
        "announcements",
        "webinars",
        "conferences",
        "speakers",
        "attendees",
        "sponsors",
        "vendors",
        "contracts",
        "agreements",
        "terms",
        "conditions",
        "privacy_policy",
        "cookies_policy",
        "legal",
        "compliance",
        "regulations",
        "licenses",
        "patents",
        "trademarks",
        "copyrights",
        "disputes",
        "settlements",
        "court_cases",
        "testimonials",
        "case_studies",
        "whitepapers",
        "ebooks",
        "downloads",
        "assets",
        "brand_assets",
        "logos",
        "icons",
        "fonts",
        "colors",
        "layouts",
        "designs",
        "prototypes",
        "wireframes",
        "mockups",
        "user_stories",
        "personas",
        "journeys",
        "use_cases",
        "requirements",
        "specifications",
        "roadmaps",
        "sprints",
        "backlogs",
        "retrospectives",
        "issues",
        "bug_reports",
        "feature_requests",
        "test_cases",
        "test_plans",
        "test_results",
        "quality_assurance",
        "deployment",
        "releases",
        "versions",
        "builds",
        "pipelines",
        "containers",
        "virtual_machines",
        "servers",
        "instances",
        "clusters",
        "microservices",
        "endpoints",
        "apis",
        "integrations",
        "plugins",
        "extensions",
        "themes",
        "widgets",
        "shortcodes",
        "blocks",
        "components",
        "libraries",
        "frameworks",
        "packages",
        "dependencies",
        "repositories",
        "commits",
        "branches",
        "tags",
        "pull_requests",
        "code_reviews",
        "merges",
        "conflicts",
        "resolutions",
        "deployments",
        "environments",
        "staging",
        "production",
        "monitoring",
        "logging",
        "alerting",
        "incident_management",
        "service_level_agreements",
        "uptime",
        "latency",
        "throughput",
        "bandwidth",
        "storage",
        "capacity",
        "utilization",
        "scaling",
        "load_balancing",
        "failover",
        "redundancy",
        "disaster_recovery",
        "business_continuity",
        "security",
        "encryption",
        "certificates",
        "keys",
        "secrets",
        "tokens",
        "authentication",
        "authorization",
        "firewalls",
        "intrusion_detection",
        "vulnerabilities",
        "threats",
        "patches",
        "updates",
        "compliance",
        "audits",
        "logs",
        "events",
    ]
    return table_names


def get_sql_table_name() -> str:
    """
    Returns N random unique table names.
    
    Args:
        N (int): Number of table names to return
        
    Returns:
        List[str]: List of N random unique table names
    """
    all_tables = get_sql_table_names()
    return random.choice(all_tables)