export ACCELERATE_DISTRIBUTED_TYPE="MULTI_GPU"
export ACCELERATE_USE_MPS_DEVICE=0
export ACCELERATE_USE_CPU=0
export ACCELERATE_MIXED_PRECISION="no"
export ACCELERATE_GPU_IDS="all"
export ACCELERATE_MULTI_GPU_BACKEND="gloo"
